[project]
name = "onboarding-guide"
version = "0.1.0"
description = "Onboarding guide for new members in CMS collaboration in EPN"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mkdocs-material>=9.6.14"]
